### ISSUE TITLE
There is no text in SophiApp

### ISSUE THREAD

**Issue by RW099** [Sophia-Community/SophiApp#45]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] SophiApp may not work on a homebrew Windows;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

If I open SophiApp I get the Main menu (privacy, personalization...) I can see the tick boxes, but there is no text about the content or function of the tickboxes - see screenshot

### Expected behavior

Text of different options, to select them

### SophiApp version

1.0.0.45 RC14

### Windows Version

Windows 10 21H2

### Logs

![Ashampoo_Snap_](https://user-images.githubusercontent.com/103029167/161733793-d00a1275-ceb6-4799-91c3-507d14fbf118.jpg)
[SophiApp-RICHARDSHP-132933654379949656.txt](https://github.com/Sophia-Community/SophiApp/files/8417201/SophiApp-RICHARDSHP-132933654379949656.txt)

**Comment by farag2** [comment]
Thank you for bug reporting. Sorry for the inconvenience 😭 , but this is really bug from our side: the problem is that you OS locale is German, then the app tries to load the German transaltion, but there is no it yet in the app! Only sidebar is translated. What you can do: open settings in the app and there will be a drop down menus. Find in one the English translation. We have been waiting for the German translation for the 4th week form one native. If youw wish you may help us with it. Cus the app is finished to be released. The only thing left is German language. 🐱 

https://github.com/Sophia-Community/SophiApp/pull/20

**Comment by farag2** [comment]
fixed. in 1.0.0.50 build
